const BLAGUES = [
  // ── Devinettes : propriété ───────────────────────────────────────────────
  {
    id: 1,
    type: 'propriete',
    label: 'Devinette',
    color: '#4ECDC4',
    question: "Je suis blanc et froid.\nJe tombe du ciel en hiver.\nLes enfants m'utilisent pour faire des bonshommes.\nQui suis-je ?",
    answer: "La neige !",
    emoji: "❄️",
    reaction: "Brrr ! Tu as trouvé très vite !",
  },
  {
    id: 2,
    type: 'propriete',
    label: 'Devinette',
    color: '#4ECDC4',
    question: "Je suis jaune et courbé comme un sourire.\nOn me pèle avant de me manger.\nJe suis le fruit préféré des singes.\nQui suis-je ?",
    answer: "La banane !",
    emoji: "🍌",
    reaction: "Ooh ooh ah ah ! Tu as trouvé !",
  },
  {
    id: 3,
    type: 'propriete',
    label: 'Devinette',
    color: '#4ECDC4',
    question: "J'ai de longues oreilles et une courte queue.\nJe saute très haut.\nJe suis doux comme un coussin.\nQui suis-je ?",
    answer: "Le lapin !",
    emoji: "🐰",
    reaction: "Hop hop hop ! C'est le lapin !",
  },
  {
    id: 4,
    type: 'propriete',
    label: 'Devinette',
    color: '#4ECDC4',
    question: "Je suis rouge et petite.\nJe pousse dans les jardins.\nJ'ai des pépins et je suis sucrée.\nQui suis-je ?",
    answer: "La fraise !",
    emoji: "🍓",
    reaction: "Miam miam ! La fraise !",
  },
  {
    id: 5,
    type: 'propriete',
    label: 'Devinette',
    color: '#4ECDC4',
    question: "J'ai une très longue trompe.\nJe suis gris et très grand.\nJe suis le plus grand animal de la savane.\nQui suis-je ?",
    answer: "L'éléphant !",
    emoji: "🐘",
    reaction: "BARRR ! Bravo, c'est l'éléphant !",
  },
  // ── Devinettes : fonction ────────────────────────────────────────────────
  {
    id: 6,
    type: 'fonction',
    label: 'Devinette',
    color: '#A29BFE',
    question: "Je sers à garder tes pieds au chaud.\nJe suis souvent perdue dans la machine à laver.\nQu'est-ce que je suis ?",
    answer: "La chaussette !",
    emoji: "🧦",
    reaction: "Ha ! Et je sens parfois un peu des pieds !",
  },
  {
    id: 7,
    type: 'fonction',
    label: 'Devinette',
    color: '#A29BFE',
    question: "Je sers à couper le papier.\nJ'ai deux trous pour les doigts.\nQu'est-ce que je suis ?",
    answer: "Les ciseaux !",
    emoji: "✂️",
    reaction: "Coupé ! Tu as bien répondu !",
  },
  {
    id: 8,
    type: 'fonction',
    label: 'Devinette',
    color: '#A29BFE',
    question: "Je sers à effacer ce que tu as écrit.\nJe suis le meilleur ami du crayon.\nQu'est-ce que je suis ?",
    answer: "La gomme !",
    emoji: "🩹",
    reaction: "Effacé ! Bravo !",
  },
  {
    id: 9,
    type: 'fonction',
    label: 'Devinette',
    color: '#A29BFE',
    question: "Je sers à te réveiller le matin.\nJe fais un bruit terrible.\nQu'est-ce que je suis ?",
    answer: "Le réveil !",
    emoji: "⏰",
    reaction: "DRING DRING DRING ! C'est l'heure !",
  },
  {
    id: 10,
    type: 'fonction',
    label: 'Devinette',
    color: '#A29BFE',
    question: "Je sers à te montrer ton visage.\nJe répète tout ce que tu fais, mais à l'envers.\nQu'est-ce que je suis ?",
    answer: "Le miroir !",
    emoji: "🪞",
    reaction: "Coucou, c'est toi dans le miroir !",
  },
  // ── Devinettes : personnification ────────────────────────────────────────
  {
    id: 11,
    type: 'perso',
    label: 'Devinette',
    color: '#FD79A8',
    question: "Je parle mais je n'ai pas de bouche.\nJe répète tout ce que tu dis, toujours après toi.\nQui suis-je ?",
    answer: "L'écho !",
    emoji: "🔊",
    reaction: "L'écho ! L'écho ! L'écho !",
  },
  {
    id: 12,
    type: 'perso',
    label: 'Devinette',
    color: '#FD79A8',
    question: "Je pousse les bateaux sur la mer.\nJe fais voler les cerfs-volants.\nJe suis invisible mais tu peux me sentir.\nQui suis-je ?",
    answer: "Le vent !",
    emoji: "💨",
    reaction: "Whoooosh ! C'est le vent !",
  },
  {
    id: 13,
    type: 'perso',
    label: 'Devinette',
    color: '#FD79A8',
    question: "Je grandis quand il y a du soleil.\nJe disparais quand il fait nuageux.\nJe te ressemble en tout, mais je suis tout noir.\nQui suis-je ?",
    answer: "Ton ombre !",
    emoji: "👤",
    reaction: "Regarde derrière toi ! C'est ton ombre !",
  },
  {
    id: 14,
    type: 'perso',
    label: 'Devinette',
    color: '#FD79A8',
    question: "Je tombe du ciel mais je ne suis pas un oiseau.\nJe mouille tout sur mon passage.\nJe fais des flaques dans la rue.\nQui suis-je ?",
    answer: "La pluie !",
    emoji: "🌧️",
    reaction: "Plouf plouf plouf ! La pluie !",
  },
  {
    id: 15,
    type: 'perso',
    label: 'Devinette',
    color: '#FD79A8',
    question: "Je danse dans la cheminée.\nJe réchauffe la maison en hiver.\nJe mange du bois mais je n'ai pas de dents.\nQui suis-je ?",
    answer: "Le feu !",
    emoji: "🔥",
    reaction: "Crépite crépite ! C'est le feu !",
  },
  // ── Blagues ──────────────────────────────────────────────────────────────
  {
    id: 16,
    type: 'blague',
    label: 'Blague',
    color: '#F7B731',
    question: "Pourquoi les vaches portent-elles des cloches ?",
    answer: "Parce que leurs cornes ne font pas de bruit !",
    emoji: "🐄",
    reaction: "Hahahaha ! Les cornes... les cloches !",
  },
  {
    id: 17,
    type: 'blague',
    label: 'Blague',
    color: '#F7B731',
    question: "Que dit un mur à un autre mur ?",
    answer: "On se retrouve au coin !",
    emoji: "🧱",
    reaction: "Hahahaha ! Au coin ! Les murs ont de l'humour !",
  },
  {
    id: 18,
    type: 'blague',
    label: 'Blague',
    color: '#F7B731',
    question: "Qu'est-ce qu'un chat tout mouillé ?",
    answer: "Un chameau ! (chat + mouillé)",
    emoji: "🐪",
    reaction: "Chat mouillé… chameau ! Tu as compris ?",
  },
  {
    id: 19,
    type: 'blague',
    label: 'Blague',
    color: '#F7B731',
    question: "Pourquoi l'épouvantail a-t-il reçu un prix ?",
    answer: "Parce qu'il était exceptionnel dans son domaine !",
    emoji: "🌾",
    reaction: "Dans son do-maine ! Hahahaha !",
  },
  {
    id: 20,
    type: 'blague',
    label: 'Blague',
    color: '#F7B731',
    question: "Qu'est-ce qu'un crocodile qui surveille des bébés ?",
    answer: "Un croco-nounou !",
    emoji: "🐊",
    reaction: "Un croco-nounou ! J'espère qu'il est doux !",
  },
];
